Manually bump Helm chart versions, rename model-server to Wizard
rungalileo/helm-charts pull request #3
Opened 2024-05-30 15:43 UTC by tyler-galileo

Renames model-server to Wizard and manually bumps all the app and chart versions.

I ran the release workflow on this branch and it succeeded:

```bash
➜  helm-charts git:(tyler/5-30-24_release) ✗ helm search repo galileo   
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                
galileo/galileo         0.2.0                           A Helm chart for Kubernetes
galileo/api             0.3.0           1.130.0         A Helm chart for Kubernetes
galileo/comet           0.2.0           0.5.4           A Helm chart for Kubernetes
galileo/model-server    0.1.0           1.16.0          A Helm chart for Kubernetes
galileo/runners         0.3.0           1.83.1          A Helm chart for Kubernetes
galileo/ui              0.3.0           2.2.83          A Helm chart for Kubernetes
galileo/wizard          0.2.0           0.64.0          A Helm chart for Kubernetes
```

Stack is up and running on https://console.helm-test.rungalileo.io/sign-in

2024-05-30 16:09 UTC, setu4993 reviewed
Looking like a good start.

I have a few questions inline, but additionally: Is the goal of this PR to bring these charts to parity? If yes, I think we need a bunch of other changes that we've incorporated in our k8s config (env vars, permissions, timeouts) that are not here.

2024-05-30 16:09 UTC, setu4993 commented on charts/wizard/templates/tests/test-connection.yaml
> +  restartPolicy: Never
What is this for?

2024-05-30 16:09 UTC, setu4993 commented on charts/wizard/templates/tests/test-connection.yaml
> +  restartPolicy: Never
What is this for?

2024-05-30 16:09 UTC, setu4993 commented on charts/wizard/README.md
> +helm install wizard ./charts/wizard --namespace wizard --create-namespace
Is this missing a value at the end for the namespace?

2024-05-30 16:09 UTC, setu4993 commented on charts/wizard/README.md
> +helm install wizard ./charts/wizard --namespace wizard --create-namespace
Is this missing a value at the end for the namespace?

2024-05-30 16:20 UTC, tyler-galileo commented on charts/galileo/Chart.yaml
> +    condition: wizard.enabled
Probably not anymore, this remains from the days where most model inference was done in Runners

2024-05-30 16:24 UTC, tyler-galileo commented on charts/galileo/values.yaml
> +wizard:
Not as the default.  If the customer is running on CPU they would specify a different value than GPU.

2024-05-30 16:24 UTC, tyler-galileo commented on charts/galileo/Chart.lock
> +generated: "2024-05-30T10:35:31.543432-05:00"
Ah, that was by me doing `helm dependency update ./charts/galileo`

2024-05-30 16:24 UTC, tyler-galileo commented on charts/wizard/README.md
> +helm install wizard ./charts/wizard --namespace wizard --create-namespace
Nope!  The namespace is specified as Wizard here, and if it doesn't exist the flag at the end will create it for us!

2024-05-30 16:24 UTC, tyler-galileo commented on charts/wizard/templates/tests/test-connection.yaml
> +  restartPolicy: Never
This was added by the default Helm chart, it could likely be removed but it's to test for a successful deployment so Helm knows what to return when the `helm deploy` command is run.

2024-05-30 16:57 UTC, ShuaiShao93 commented on charts/galileo/Chart.lock
>  dependencies:
Maybe not in this PR, but can we change the postgres to use an operator that supports in-place upgrade, like https://github.com/zalando/postgres-operator? It was a huge pain to upgrade it last time

2024-05-31 14:49 UTC, tyler-galileo commented
> I have a few questions inline, but additionally: Is the goal of this PR to bring these charts to parity? If yes, I think we need a bunch of other changes that we've incorporated in our k8s config (env vars, permissions, timeouts) that are not here.

It's working towards that, but mainly just trying to update the underlying application versions

2024-05-31 18:30 UTC, setu4993 commented
> > I have a few questions inline, but additionally: Is the goal of this PR to bring these charts to parity? If yes, I think we need a bunch of other changes that we've incorporated in our k8s config (env vars, permissions, timeouts) that are not here.
> 
> It's working towards that, but mainly just trying to update the underlying application versions

I would recommend against that... I think we should get config updated before application versions. Why? That ensures that the chart can be used. Without that, the chart will just fail to deploy.

2024-06-04 17:06 UTC, setu4993 requested changes
Thanks for updating this, @tyler-galileo. But I think it's still not at parity with the config we have in `deploy`. Looking from the first page, we are missing atleast the changes from these, maybe more:
- https://github.com/rungalileo/deploy/pull/1318
- https://github.com/rungalileo/deploy/pull/1317
- https://github.com/rungalileo/deploy/pull/1319
- https://github.com/rungalileo/deploy/pull/1311
- https://github.com/rungalileo/deploy/pull/1296

Can we do an export from both, compare the diff and bring the config here to parity, please?

2024-06-04 17:06 UTC, setu4993 commented on charts/api/Chart.yaml
> +version: 0.4.0
Why did we skip 0.3.0?

2024-06-04 17:06 UTC, setu4993 commented on charts/api/templates/minio-secret.yaml
> +    "helm.sh/hook": "pre-install"
Curious what this does?

2024-06-04 17:06 UTC, setu4993 commented on charts/api/values.yaml
> +  endpointURL: "minio.galileo.svc.cluster.local:9000"
Is there a reason we're removing the `http` from here but adding that in the `deployment.yaml` during extrapolation?

2024-06-04 17:06 UTC, setu4993 commented on charts/wizard/values.yaml
> +        key: HF_TOKEN
Are we missing `GALILEO_CUSTOMER_NAME` here?

2024-06-04 17:07 UTC, tyler-galileo commented on charts/api/Chart.yaml
> +version: 0.4.0
We didn't, but within this particular branch this is the second version bump so the diff will show it skipping a version.

2024-06-04 17:09 UTC, setu4993 commented on charts/api/Chart.yaml
> +version: 0.4.0
If the version is only in a branch, does it matter? Only released versions should matter, right?

2024-06-04 17:10 UTC, tyler-galileo commented on charts/api/values.yaml
> +  endpointURL: "minio.galileo.svc.cluster.local:9000"
Yes, there are places that use this that can't have that prefix (specifically `GALILEO_MINIO_FQDN`).

2024-06-04 17:12 UTC, tyler-galileo commented on charts/api/Chart.yaml
> +version: 0.4.0
Correct, but a Helm chart version with those *was* released from this branch to test the release GitHub action still worked as expected (see the description).

2024-06-04 17:14 UTC, setu4993 commented on charts/api/Chart.yaml
> +version: 0.4.0
Okay. Can we avoid releasing from the branch in the future? We can just do alpha / beta releases from branches. Would be much safer.

2024-06-04 17:16 UTC, tyler-galileo commented on charts/api/Chart.yaml
> +version: 0.4.0
Yup, agreed

2024-06-04 20:48 UTC, tyler-galileo commented on charts/wizard/values.yaml
> +        key: HF_TOKEN
Added

2024-06-04 22:54 UTC, setu4993 approved these changes
Looks good for now.

Let's continue chipping away at the diff, though. Off the top of my head, stuff we're still missing:
- Clickhouse
- OpenTelemetry

2024-06-05 14:34 UTC, merged